/*
 * This source file was generated by the Gradle 'init' task
 */
package gradlewithjavafx;

public class App extends HelloApplication
{
    
    public static void main(String[] args) {
        HelloApplication.main(args);
    }
}
